import { describe, expect, it } from "vitest";
import { formatTimestamp } from "../src/timestamp";
import { renderTranscriptMarkdown } from "../src/transcript-markdown";

describe("timestamps and transcript Markdown", () => {
  it("floors milliseconds without seeking after a cue starts", () => {
    expect(formatTimestamp(126999)).toEqual({ seconds: 126, label: "00:02:06" });
  });

  it("renders source data and timestamp links", () => {
    const markdown = renderTranscriptMarkdown(
      { id: "Kf1dYpnH-N4", canonicalUrl: "https://www.youtube.com/watch?v=Kf1dYpnH-N4" },
      "영상 제목",
      { id: "ko", languageCode: "ko", label: "한국어", baseUrl: "https://example.test", isAutoGenerated: false },
      [{ startMs: 10000, text: "첫 번째 자막" }]
    );
    expect(markdown).toContain("Transcript: Manual");
    expect(markdown).toContain("[00:00:10](https://www.youtube.com/watch?v=Kf1dYpnH-N4#t=10)");
  });
});
