import { describe, expect, it } from "vitest";
import { internal, YouTubeCaptionProvider } from "../src/youtube-captions";

const playerHtml = `<script>var ytInitialPlayerResponse = {"videoDetails":{"title":"Test title"},"captions":{"playerCaptionsTracklistRenderer":{"captionTracks":[{"baseUrl":"https://example.test/captions?lang=en","languageCode":"en","name":{"simpleText":"English"}},{"baseUrl":"https://example.test/captions?lang=ko","languageCode":"ko","kind":"asr","name":{"runs":[{"text":"한국어"}]}}]}}};</script>`;

describe("YouTube caption provider", () => {
  it("extracts the initial player response", () => {
    expect(internal.playerResponseFromHtml(playerHtml)?.videoDetails).toEqual({ title: "Test title" });
  });

  it("classifies manual and auto-generated tracks then parses json3 cues", async () => {
    const provider = new YouTubeCaptionProvider(async (url) => {
      if (url.includes("watch")) return { status: 200, text: playerHtml };
      return { status: 404, text: "" };
    }, async (_videoId, _track) => [{ startMs: 1234, text: "hello world" }]);
    const data = await provider.getVideoCaptionData("Kf1dYpnH-N4");
    expect(data.tracks.map((track) => track.isAutoGenerated)).toEqual([false, true]);
    await expect(provider.getTranscript("Kf1dYpnH-N4", data.tracks[0])).resolves.toEqual([{ startMs: 1234, text: "hello world" }]);
  });
});
