import { TranscriptCue } from "./types";

declare const __TRANSCRIPT_HELPER_SOURCE__: string;

export async function fetchPoTokenTranscript(videoId: string, languageCode: string, isAutoGenerated: boolean): Promise<TranscriptCue[]> {
  const remote = (window as unknown as { electron?: { remote?: { BrowserWindow?: new (options: unknown) => HiddenWindow } } }).electron?.remote;
  if (!remote?.BrowserWindow) throw new Error("Obsidian could not create the isolated transcript window.");
  const hiddenWindow = new remote.BrowserWindow({
    show: false,
    webPreferences: { nodeIntegration: false, contextIsolation: true, sandbox: true }
  });
  try {
    await hiddenWindow.loadURL(`https://www.youtube.com/watch?v=${encodeURIComponent(videoId)}&hl=en`);
    const expression = `${__TRANSCRIPT_HELPER_SOURCE__}\nCYTTranscriptHelper.fetchTrackTranscript(${JSON.stringify(videoId)}, ${JSON.stringify(languageCode)}, ${JSON.stringify(isAutoGenerated)})`;
    return await hiddenWindow.webContents.executeJavaScript(expression, true) as TranscriptCue[];
  } finally {
    if (!hiddenWindow.isDestroyed()) hiddenWindow.destroy();
  }
}

interface HiddenWindow {
  webContents: { executeJavaScript(code: string, userGesture?: boolean): Promise<unknown> };
  loadURL(url: string): Promise<void>;
  isDestroyed(): boolean;
  destroy(): void;
}
