import { ButtonComponent, Modal, Setting } from "obsidian";
import { CaptionTrack } from "./types";

export class CaptionTrackModal extends Modal {
  private resolveChoice: ((track: CaptionTrack | null) => void) | null = null;

  constructor(app: import("obsidian").App, private readonly tracks: CaptionTrack[]) {
    super(app);
  }

  choose(): Promise<CaptionTrack | null> {
    return new Promise((resolve) => {
      this.resolveChoice = resolve;
      this.open();
    });
  }

  onOpen(): void {
    this.titleEl.setText("자막 선택");
    this.contentEl.createEl("p", { text: "가져올 자막을 선택하세요." });
    for (const track of this.tracks) {
      const description = `${track.languageCode} · ${track.isAutoGenerated ? "자동 생성" : "수동"}`;
      new Setting(this.contentEl)
        .setName(track.label)
        .setDesc(description)
        .addButton((button: ButtonComponent) => button.setButtonText("추출").setCta().onClick(() => this.finish(track)));
    }
  }

  onClose(): void {
    this.contentEl.empty();
    if (this.resolveChoice) this.finish(null);
  }

  private finish(track: CaptionTrack | null): void {
    const resolve = this.resolveChoice;
    this.resolveChoice = null;
    if (this.modalEl.isShown()) this.close();
    resolve?.(track);
  }
}
