import { CaptionTrack, TranscriptCue, YouTubeVideo } from "./types";
import { formatTimestamp } from "./timestamp";

function escapeText(value: string): string {
  return value
    .replace(/\\/g, "\\\\")
    .replace(/[\\[\\]]/g, "\\$&")
    .replace(/</g, "\\<")
    .replace(/>/g, "\\>");
}

export function renderTranscriptMarkdown(
  video: YouTubeVideo,
  title: string | undefined,
  track: CaptionTrack,
  cues: TranscriptCue[]
): string {
  const heading = title?.trim() ? escapeText(title.trim()) : "YouTube Transcript";
  const transcriptKind = track.isAutoGenerated ? "Auto-generated" : "Manual";
  const entries = cues.map((cue) => {
    const timestamp = formatTimestamp(cue.startMs);
    return `[${timestamp.label}](${video.canonicalUrl}#t=${timestamp.seconds})\n\n${escapeText(cue.text)}`;
  });
  return [
    `# ${heading}`,
    "",
    `Source: ${video.canonicalUrl}`,
    `Language: ${escapeText(track.label)}`,
    `Transcript: ${transcriptKind}`,
    "",
    "## Transcript",
    "",
    entries.join("\n\n"),
    "",
    "<!-- canvas-youtube-transcript -->"
  ].join("\n");
}
