import { BG, buildURL, GOOG_API_KEY } from "bgutils-js";

const WEB_USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36";
const REQUEST_KEY = "O43z0dpjhgX20SCx4KAo";

interface CaptionTrackData {
  baseUrl: string;
  languageCode: string;
  kind?: string;
}

function parsePlayerResponse(html: string): Record<string, unknown> | null {
  const marker = "ytInitialPlayerResponse = ";
  const markerIndex = html.indexOf(marker);
  if (markerIndex === -1) return null;
  const start = html.indexOf("{", markerIndex + marker.length);
  let depth = 0;
  let inString = false;
  let escaped = false;
  for (let index = start; index < html.length; index += 1) {
    const char = html[index];
    if (escaped) {
      escaped = false;
      continue;
    }
    if (char === "\\") {
      escaped = true;
      continue;
    }
    if (char === '"') inString = !inString;
    if (inString) continue;
    if (char === "{") depth += 1;
    if (char === "}") {
      depth -= 1;
      if (depth === 0) {
        try {
          return JSON.parse(html.slice(start, index + 1)) as Record<string, unknown>;
        } catch {
          return null;
        }
      }
    }
  }
  return null;
}

async function mintPoToken(visitorData: string, videoId: string): Promise<string> {
  const request = (input: RequestInfo | URL, init?: RequestInit) => globalThis.fetch(input, init);
  const config = { fetch: request, globalObj: globalThis, requestKey: REQUEST_KEY, identifier: visitorData };
  const challenge = await BG.Challenge.create(config);
  const interpreter = challenge?.interpreterJavascript?.privateDoNotAccessOrElseSafeScriptWrappedValue;
  if (!challenge || !interpreter) throw new Error("BotGuard challenge could not be created.");
  const trustedTypes = (globalThis as unknown as {
    trustedTypes?: { createPolicy(name: string, rules: { createScript(value: string): string }): { createScript(value: string): unknown } };
  }).trustedTypes;
  const executable = trustedTypes?.createPolicy("canvas-youtube-transcript-botguard", { createScript: (value) => value }).createScript(interpreter) ?? interpreter;
  // YouTube requires a TrustedScript here. `Function` still coerces this to a
  // string under its policy, while direct evaluation preserves the trusted value.
  eval(executable as string);
  const client = await BG.BotGuardClient.create({ program: challenge.program, globalName: challenge.globalName, globalObj: globalThis });
  type SnapshotOptions = Parameters<typeof client.snapshot>[0];
  const webPoSignalOutput: NonNullable<SnapshotOptions["webPoSignalOutput"]> = [];
  const snapshot = await client.snapshot({ webPoSignalOutput });
  const response = await fetch(buildURL("GenerateIT", false), {
    method: "POST",
    headers: { "Content-Type": "application/json+protobuf", "x-goog-api-key": GOOG_API_KEY, "x-user-agent": "grpc-web-javascript/0.1" },
    body: JSON.stringify([REQUEST_KEY, snapshot])
  });
  if (!response.ok) throw new Error(`PoToken request failed (${response.status}).`);
  const payload = (await response.json()) as [string?];
  const integrityToken = payload[0];
  if (!integrityToken) throw new Error("PoToken response was empty.");
  const minter = await BG.WebPoMinter.create({ integrityToken }, webPoSignalOutput);
  return minter.mintAsWebsafeString(videoId);
}

export async function fetchTrackTranscript(videoId: string, languageCode: string, isAutoGenerated: boolean): Promise<Array<{ startMs: number; text: string }>> {
  const page = await fetch(`https://www.youtube.com/watch?v=${encodeURIComponent(videoId)}&hl=en&bpctr=9999999999&has_verified=1`, {
    headers: { "User-Agent": WEB_USER_AGENT, "Accept-Language": "en-US,en;q=0.9", Cookie: "CONSENT=YES+cb; SOCS=CAESEwgDEgk0ODE3Nzk3MjQaAmVuIAEaBgiA_LyaBg" }
  });
  if (!page.ok) throw new Error(`YouTube watch page failed (${page.status}).`);
  const html = await page.text();
  const player = parsePlayerResponse(html);
  if (!player) throw new Error("YouTube watch page could not be parsed.");
  const captions = player.captions as { playerCaptionsTracklistRenderer?: { captionTracks?: CaptionTrackData[] } } | undefined;
  const tracks = captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
  const track = tracks.find((candidate) => candidate.languageCode === languageCode && (candidate.kind === "asr") === isAutoGenerated);
  if (!track) throw new Error("The selected caption track is no longer available.");
  const visitorData = (html.match(/"visitorData":"([^"]+)"/) ?? [])[1] ?? "";
  const poToken = await mintPoToken(visitorData, videoId);
  const captionUrl = new URL(track.baseUrl);
  captionUrl.searchParams.set("fmt", "json3");
  captionUrl.searchParams.set("pot", poToken);
  captionUrl.searchParams.set("c", "WEB");
  const response = await fetch(captionUrl, { headers: { "User-Agent": WEB_USER_AGENT, Origin: "https://www.youtube.com" } });
  if (!response.ok) throw new Error(`Caption download failed (${response.status}).`);
  const payload = (await response.json()) as { events?: Array<{ tStartMs?: number; segs?: Array<{ utf8?: string }> }> };
  const cues = (payload.events ?? [])
    .map((event) => {
      const text = (event.segs ?? []).map((segment) => segment.utf8 ?? "").join("").replace(/\s+/g, " ").trim();
      return typeof event.tStartMs === "number" && text ? { startMs: event.tStartMs, text } : null;
    })
    .filter((cue): cue is { startMs: number; text: string } => cue !== null);
  if (!cues.length) throw new Error("The selected caption track was empty.");
  return cues;
}
