export interface YouTubeVideo {
  id: string;
  canonicalUrl: string;
}

export interface CaptionTrack {
  id: string;
  languageCode: string;
  label: string;
  baseUrl: string;
  isAutoGenerated: boolean;
}

export interface TranscriptCue {
  startMs: number;
  text: string;
}

export interface VideoCaptionData {
  title?: string;
  tracks: CaptionTrack[];
}

export class UserFacingError extends Error {
  constructor(
    readonly code:
      | "url-not-found"
      | "invalid-url"
      | "video-id-failed"
      | "no-captions"
      | "caption-fetch-failed"
      | "network-failed"
      | "caption-parse-failed"
      | "canvas-not-found"
      | "canvas-node-create-failed",
    message: string,
    readonly cause?: unknown
  ) {
    super(message);
    this.name = "UserFacingError";
  }
}
