import { requestUrl } from "obsidian";
import { fetchPoTokenTranscript } from "./potoken-transcript";
import { CaptionTrack, TranscriptCue, UserFacingError, VideoCaptionData } from "./types";

interface RequestResult {
  status: number;
  text: string;
}

type TextRequest = (url: string) => Promise<RequestResult>;
type TranscriptRequest = (videoId: string, track: CaptionTrack) => Promise<TranscriptCue[]>;

function readableTrackName(track: Record<string, unknown>, languageCode: string): string {
  const name = track.name as { simpleText?: string; runs?: Array<{ text?: string }> } | undefined;
  const text = name?.simpleText ?? name?.runs?.map((run) => run.text ?? "").join("");
  return text?.trim() || languageCode;
}

function extractJsonObject(source: string, marker: string): Record<string, unknown> | null {
  const markerIndex = source.indexOf(marker);
  if (markerIndex === -1) return null;
  const start = source.indexOf("{", markerIndex + marker.length);
  if (start === -1) return null;
  let depth = 0;
  let quote = "";
  let escaped = false;
  for (let index = start; index < source.length; index += 1) {
    const char = source[index];
    if (quote) {
      if (escaped) escaped = false;
      else if (char === "\\") escaped = true;
      else if (char === quote) quote = "";
      continue;
    }
    if (char === '"' || char === "'") {
      quote = char;
      continue;
    }
    if (char === "{") depth += 1;
    if (char === "}") {
      depth -= 1;
      if (depth === 0) {
        try {
          return JSON.parse(source.slice(start, index + 1)) as Record<string, unknown>;
        } catch {
          return null;
        }
      }
    }
  }
  return null;
}

function playerResponseFromHtml(html: string): Record<string, unknown> | null {
  return (
    extractJsonObject(html, "ytInitialPlayerResponse =") ??
    extractJsonObject(html, "ytInitialPlayerResponse=") ??
    extractJsonObject(html, "var ytInitialPlayerResponse =")
  );
}

export class YouTubeCaptionProvider {
  constructor(
    private readonly request: TextRequest = requestText,
    private readonly transcriptRequest: TranscriptRequest = (videoId, track) => fetchPoTokenTranscript(videoId, track.languageCode, track.isAutoGenerated)
  ) {}

  async getVideoCaptionData(videoId: string): Promise<VideoCaptionData> {
    const url = `https://www.youtube.com/watch?v=${encodeURIComponent(videoId)}&hl=en`;
    let response: RequestResult;
    try {
      response = await this.request(url);
    } catch (error) {
      throw new UserFacingError("network-failed", "YouTube에 연결할 수 없습니다. 네트워크 상태를 확인해 주세요.", error);
    }
    if (response.status < 200 || response.status >= 300) {
      throw new UserFacingError("caption-fetch-failed", "YouTube 자막 정보를 가져오지 못했습니다.");
    }
    const player = playerResponseFromHtml(response.text);
    if (!player) {
      throw new UserFacingError("caption-parse-failed", "YouTube 자막 정보를 해석하지 못했습니다.");
    }
    const captions = player.captions as { playerCaptionsTracklistRenderer?: { captionTracks?: Array<Record<string, unknown>> } } | undefined;
    const tracks = captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
    const parsedTracks = tracks
      .map((track, index): CaptionTrack | null => {
        const baseUrl = typeof track.baseUrl === "string" ? track.baseUrl : "";
        const languageCode = typeof track.languageCode === "string" ? track.languageCode : "";
        if (!baseUrl || !languageCode) return null;
        return {
          id: typeof track.vssId === "string" ? track.vssId : `${languageCode}-${index}`,
          languageCode,
          label: readableTrackName(track, languageCode),
          baseUrl,
          isAutoGenerated: track.kind === "asr"
        };
      })
      .filter((track): track is CaptionTrack => track !== null)
      .sort((left, right) => Number(left.isAutoGenerated) - Number(right.isAutoGenerated) || left.label.localeCompare(right.label));
    if (!parsedTracks.length) {
      throw new UserFacingError("no-captions", "이 영상에서 사용 가능한 자막을 찾을 수 없습니다.");
    }
    const details = player.videoDetails as { title?: string } | undefined;
    return { title: details?.title, tracks: parsedTracks };
  }

  async getTranscript(videoId: string, track: CaptionTrack): Promise<TranscriptCue[]> {
    try {
      return await this.transcriptRequest(videoId, track);
    } catch (error) {
      throw new UserFacingError("caption-parse-failed", "자막 내용을 해석하지 못했습니다.", error);
    }
  }
}

async function requestText(url: string): Promise<RequestResult> {
  const response = await requestUrl({ url, headers: { "Accept-Language": "en-US,en;q=0.9" } });
  return { status: response.status, text: response.text };
}

export const internal = { extractJsonObject, playerResponseFromHtml };
